23.06 09:16:35> Admin Command Error: manage.py localize
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/lapshov/Documents/dve/enot/enot_app/management/commands/localize.py", line 27, in handle
    t.departure = tz.localize(t.departure)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/pytz/tzinfo.py", line 304, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
23.06 09:59:01> Admin Command Error: manage.py localize
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/lapshov/Documents/dve/enot/enot_app/management/commands/localize.py", line 29, in handle
    t.save()
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/base.py", line 889, in _save_table
    forced_update)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/base.py", line 939, in _do_update
    return filtered._update(values) > 0
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/query.py", line 654, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1148, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 824, in execute_sql
    sql, params = self.as_sql()
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1112, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 755, in get_db_prep_save
    prepared=False)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 1439, in get_db_prep_value
    return connection.ops.adapt_datetimefield_value(value)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/db/backends/mysql/operations.py", line 149, in adapt_datetimefield_value
    raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
23.06 09:59:29> Admin Command Error: manage.py localize
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/lapshov/Documents/dve/enot/enot_app/management/commands/localize.py", line 27, in handle
    t.departure = tz.localize(t.departure)
  File "/Users/lapshov/Documents/dve/lib/python3.4/site-packages/pytz/tzinfo.py", line 304, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
23.06 10:51:22> Started trip loader task
23.06 10:51:22> 1: [122897] СПЛИТ | 14д | 2035 км | 14351р | R1251
23.06 10:51:22> 2: [122757] РИМ | 15д | 2377 км | 11170р | R1200
23.06 10:51:22> 3: [122807] РИО-ДЕ-ЖАНЕЙРО | 28д | 11542 км | 51861р | R1137
23.06 10:51:22> 4: [122777] ПАРИЖ | 6д | 2487 км | 12121р | R1035
23.06 10:51:22> 5: [122868] ЛОНДОН | 15д | 2489 км | 12343р | R903
23.06 10:51:22> 6: [122837] СТАМБУЛ | 186д | 1764 км | 7035р | R891
23.06 11:01:21> Bed time! zzz...
23.06 11:15:51> Bed time! zzz...
23.06 11:31:07> Bed time! zzz...
23.06 11:45:42> Bed time! zzz...
23.06 12:01:37> Bed time! zzz...
23.06 12:15:53> Bed time! zzz...
23.06 12:31:00> Bed time! zzz...
23.06 12:45:42> Bed time! zzz...
23.06 13:01:24> Bed time! zzz...
23.06 13:15:53> Bed time! zzz...
23.06 13:31:05> Bed time! zzz...
23.06 13:45:41> Bed time! zzz...
23.06 14:01:14> Bed time! zzz...
23.06 14:15:58> Bed time! zzz...
23.06 14:30:53> Bed time! zzz...
23.06 14:45:42> Bed time! zzz...
23.06 15:01:03> Bed time! zzz...
23.06 15:15:51> Bed time! zzz...
23.06 15:30:56> Bed time! zzz...
23.06 15:45:38> Bed time! zzz...
23.06 16:01:59> Bed time! zzz...
23.06 16:15:57> Bed time! zzz...
23.06 16:30:58> Bed time! zzz...
23.06 16:45:37> Bed time! zzz...
23.06 17:01:17> Bed time! zzz...
23.06 17:15:50> Bed time! zzz...
23.06 17:30:56> Bed time! zzz...
23.06 17:45:34> Bed time! zzz...
23.06 18:01:13> Bed time! zzz...
23.06 18:15:40> Bed time! zzz...
23.06 18:30:52> Bed time! zzz...
23.06 18:45:35> Bed time! zzz...
23.06 19:01:01> Bed time! zzz...
23.06 19:15:45> Bed time! zzz...
23.06 19:30:55> Bed time! zzz...
23.06 19:45:39> Bed time! zzz...
23.06 20:01:33> Bed time! zzz...
23.06 20:15:56> Bed time! zzz...
23.06 20:31:07> Bed time! zzz...
23.06 20:45:37> Bed time! zzz...
23.06 21:01:24> Bed time! zzz...
23.06 21:15:53> Bed time! zzz...
23.06 21:30:52> Bed time! zzz...
23.06 21:45:39> Bed time! zzz...
23.06 22:01:18> Bed time! zzz...
23.06 22:15:57> Bed time! zzz...
23.06 22:31:06> Bed time! zzz...
23.06 22:45:41> Bed time! zzz...
23.06 23:01:21> Bed time! zzz...
23.06 23:15:55> Bed time! zzz...
23.06 23:30:51> Bed time! zzz...
23.06 23:45:48> Bed time! zzz...
